structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  dashboard: ./advanced-setting/logging-monitoring/monitor-panel.md
  user_tree: ./advanced-setting/users/user-tree.md
  ad: ./advanced-setting/users/active-directory.md
  ald_pro: ./advanced-setting/users/ald.md
  authorization: ./advanced-setting/users/authorization/README.md
  telegram_bot: ./advanced-setting/logging-monitoring/connection-external-services.md
  snmp: ./advanced-setting/logging-monitoring/connection-external-services.md
  zabbix: ./advanced-setting/logging-monitoring/connection-external-services.md
  firewall: ./advanced-setting/traffic-blocking/firewall.md
  ids_ips: ./advanced-setting/traffic-blocking/ips.md
  object: ./ advanced-setting/server-management/aliases.md
  network_interface: ./advanced-setting/server-management/server-configuration-management.md
  dns: ./advanced-setting/server-management/dns.md
  ntp: ./advanced-setting/server-management/ntp.md
  certificate: ./advanced-setting/server-management/certificates.md
  custom_ssl: 
  logs: ./advanced-setting/logging-monitoring/log.md
  security_events: ./advanced-setting/logging-monitoring/events-reports.md
  admin_logs: ./advanced-setting/logging-monitoring/log.md
  authorization_log: ./advanced-setting/logging-monitoring/events-reports.md
  reports_designer: ./advanced-setting/logging-monitoring/events-reports.md
  syslog: ./advanced-setting/logging-monitoring/log.md
  admins: ./advanced-setting/server-management/management-admins.md
  server_update: ./advanced-setting/server-management/server-update.md
  backup: ./advanced-setting/server-management/backup.md
  terminal: ./advanced-setting/server-management/terminal.md
  license_management: ./advanced-setting/server-management/binding-license.md
  additionally: ./advanced-setting/server-management/language-time-management.md