structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  dashboard: 
  user_tree: 
  ad: 
  ald_pro: 
  authorized: 
  ip_checker: 
  telegram_bot: 
  snmp: 
  zabbix: 
  firewall: 
  ids_ips: 
  object: 
  network_interface: 
  dns: 
  certificate: 
  custom_ssl: 
  logs: 
  security_events: 
  admin_logs: 
  authorization_log: 
  reports_designer: 
  syslog: 
  admins: 
  server_update: 
  backup: 
  terminal: 
  license_management: 
  additionally: 