structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  dashboard: ./advanced-setting/logging-monitoring/monitor-panel.md
  user_tree: ./advanced-setting/users/user-tree.md
  user_authorization: ./advanced-setting/users/authorization/README.md
  ad: ./advanced-setting/users/active-directory.md
  ald_pro: ./advanced-setting/users/ald.md
  authorized: ./advanced-setting/logging-monitoring/authorization-info.md
  telegram_bot: ./advanced-setting/logging-monitoring/connection-external-services.md
  snmp: ./advanced-setting/logging-monitoring/connection-external-services.md
  zabbix: ./advanced-setting/logging-monitoring/connection-external-services.md
  firewall: ./advanced-setting/control-blocking/firewall.md
  ids_ips: ./advanced-setting/control-blocking/ips.md
  routing: ./advanced-setting/control-blocking/routing.md
  content_filter_security_profiles: ./advanced-setting/control-blocking/content-filter.md
  object: ./advanced-setting/server-management/aliases.md
  network_interface: ./advanced-setting/server-management/server-configuration-management.md
  dns: ./advanced-setting/server-management/dns.md
  ntp: ./advanced-setting/server-management/ntp.md
  certificate: ./advanced-setting/server-management/certificates.md
  custom_ssl: ./advanced-setting/server-management/upload-own-ssl.md
  logs: ./advanced-setting/logging-monitoring/log.md
  security_events: ./advanced-setting/logging-monitoring/security-events.md
  admin_logs: ./advanced-setting/logging-monitoring/admins-actions.md
  authorization_log: ./advanced-setting/logging-monitoring/authorization-log.md
  reports_designer: ./advanced-setting/logging-monitoring/report-designer.md
  syslog: ./advanced-setting/logging-monitoring/log.md
  admins: ./advanced-setting/server-management/management-admins.md
  server_update: ./advanced-setting/server-management/server-update.md
  backup: ./advanced-setting/server-management/backup.md
  terminal: ./advanced-setting/server-management/terminal.md
  license_management: ./advanced-setting/server-management/binding-license.md
  additionally: ./advanced-setting/server-management/language-time-management.md
  application_control_security_profiles: ./advanced-setting/control-blocking/security-profiles.md
  tls_inspection_security_profiles: ./advanced-setting/control-blocking/tls-inspection-security-profiles.md
  bgp: ./advanced-setting/control-blocking/bgp.md