structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  ad_authorization: ./settings/users/active-directory/README.md
  additionally: ./settings/services/additionally.md
  admins: ./settings/access-rules/admins.md
  antivirus: ./settings/access-rules/antivirus.md
  application_control: ./settings/access-rules/application-control.md
  backup: ./service/backup.md
  balancing_and_reserving: ./settings/connection-to-provider/multiple-simultaneous-connections.md
  certificate: ./settings/services/certificates/README.md
  cluster: ./cluster.md
  content_filter: .settings/access-rules/content-filter/README.md
  device_detection: ./services/device-discovery.md
  dhcp: ./settings/service/dhcp.md
  firewall: ./settings/access-rules/firewall.md
  https_filtration: ./settings/access-rules/content-filter/filtering-https-traffic.md
  ids_ips: ./settings/access-rules/ips.md
  install: ./installation-process.md
  ipsec: ./settings/services/vpn-tunnel-protocols/site-to-site/ipsec/README.md
  license: ./service/server-registration.md
  network_interface: ./settings/connection-to-provider/README.md
  dns: ./settings/services/dns.md
  object: ./settings/access-rules/aliases.md
  portmapping: ./settings/publishing-resources/portmapping.md
  post: ./settings/mail/README.md
  powershell: ./settings/services/vpn-tunnel-protocols/client-to-site/running-powershell-scripts.md
  proxy: ./settings/services/proxy/README.md
  report: ./settings/reports/README.md
  reverse_proxy: ./settings/services/reverse-proxy.md
  routing: ./settings/services/routing.md
  server_update: ./service/server-update.md
  snmp: ./settings/monitor/snmp.md
  speed_limit: ./settings/access-rules/shaper.md
  support: ./service/remote-assistant.md
  syslog: ./settings/monitor/syslog.md
  telegram-bot: ./settings/monitor/telegram-bot.md
  terminal: ./terminal.md
  usb: ./usb.md
  user_authorization: ./settings/users/authorization/README.md
  user_management: ./settings/users/README.md
  user_quota: ./settings/access-rules/quotas.md
  vpn_authorization: ./settings/services/vpn-tunnel-protocols/client-to-site/README.md
  zabbix: ./settings/monitor/zabbix.md
