structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  cc: ./settings/server-management/central-console/README.md
  cc_firewall: ./settings/server-management/central-console/policies-and-objects.md
  cc_application_control: ./settings/server-management/central-console/policies-and-objects.md
  cc_content_filter: ./settings/server-management/central-console/policies-and-objects.md
  cc_aliases: ./settings/server-management/central-console/policies-and-objects.md
  cc_shaper: ./settings/server-management/central-console/policies-and-objects.md
  cc_interfaces: ./settings/server-management/central-console/services.md
  cc_routing: ./settings/server-management/central-console/services.md
  cc_certs: ./settings/server-management/central-console/certificates/certificates.md
  cc_ddns: ./settings/server-management/central-console/services.md
  cc_admins: ./settings/server-management/central-console/server-management.md
  cc_selfupdate: ./settings/server-management/central-console/server-management.md
  cc_backup: ./settings/server-management/central-console/server-management.md
  cc_web_terminal: ./settings/server-management/central-console/server-management.md
  cc_characteristics: ./settings/server-management/central-console/server-management.md
  cc_additionally: ./settings/server-management/central-console/server-management.md 