structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  dashboard: ./settings/logging-monitoring/monitor-panel.md
  user_tree: ./settings/users/user-tree.md
  user_authorization: ./settings/users/authorization/README.md
  ad: ./settings/users/active-directory/README.md
  ald_pro: ./settings/users/ald.md
  authorized: ./settings/logging-monitoring/authorization-info.md
  telegram_bot: ./settings/logging-monitoring/connection-external-services.md
  snmp: ./settings/logging-monitoring/connection-external-services.md
  zabbix: ./settings/logging-monitoring/connection-external-services.md
  firewall: ./settings/control-blocking/firewall.md
  ids_ips: ./settings/control-blocking/ips.md
  routing: ./settings/control-blocking/routing.md
  object: ./settings/server-management/aliases.md
  network_interface: ./settings/server-management/server-configuration-management.md
  dns: ./settings/server-management/dns.md
  ntp: ./settings/server-management/ntp.md
  certificate: ./settings/server-management/certificates.md
  custom_ssl: ./settings/server-management/upload-own-ssl.md
  logs: ./settings/logging-monitoring/log.md
  security_events: ./settings/logging-monitoring/security-events.md
  admin_logs: ./settings/logging-monitoring/admins-actions.md
  authorization_log: ./settings/logging-monitoring/authorization-log.md
  reports_designer: ./settings/logging-monitoring/report-designer.md
  syslog: ./settings/logging-monitoring/log.md
  admins: ./settings/server-management/management-admins.md
  server_update: ./settings/server-management/server-update.md
  backup: ./settings/server-management/backup.md
  terminal: ./settings/server-management/terminal.md
  license_management: ./settings/server-management/binding-license.md
  additionally: ./settings/server-management/language-time-management.md
  application_control_security_profiles: ./settings/control-blocking/security-profiles/application-control/README.md
  tls_inspection_security_profiles: ./settings/control-blocking/security-profiles/tls-inspection-security-profiles.md
  content_filter_security_profiles: ./settings/control-blocking/security-profiles/content-filter-profiles.md
  bgp: ./settings/control-blocking/bgp.md