structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  dashboard: ./settings/monitor-panel.md
  user_tree: ./settings/users/user-tree.md
  user_authorization: ./settings/users/authorization/README.md
  ad: ./settings/users/active-directory/README.md
  ald_pro: ./settings/users/ald.md
  authorized: ./settings/monitor/authorization-info.md
  telegram_bot: ./settings/monitor/telegram-bot.md
  snmp: ./settings/monitor/snmp.md
  zabbix: ./settings/monitor/zabbix.md
  firewall: ./settings/access-rules/firewall.md
  ids_ips: ./settings/access-rules/ips.md
  routing: ./settings/services/routing.md
  object: ./settings/access-rules/aliases.md
  network_interface: ./settings/services/server-configuration-management.md
  dns: ./settings/services/dns.md
  ntp: ./settings/services/ntp.md
  certificate: ./settings/services/certificates/README.md
  custom_ssl: ./settings/services/certificates/upload-own-ssl.md
  logs: ./settings/reports/log.md
  security_events: ./settings/reports/security-events.md
  admin_logs: ./settings/reports/admins-actions.md
  authorization_log: ./settings/reports/authorization-log.md
  reports_designer: ./settings/reports/report-designer.md
  syslog: ./settings/reports/syslog.md
  admins: ./settings/server-management/management-admins.md
  server_update: ./settings/server-management/server-update.md
  backup: ./settings/server-management/backup.md
  terminal: ./settings/server-management/terminal.md
  license_management: ./settings/server-management/binding-license.md
  additionally: ./settings/server-management/additionaly.md
  application_control_security_profiles: ./settings/security-profiles/application-control-profiles.md
  tls_inspection_security_profiles: ./settings/security-profiles/tls-inspection-security-profiles.md
  content_filter_security_profiles: ./settings/security-profiles/content-filter-profiles.md
  bgp: ./settings/services/bgp.md
  source_port: ./settings/access-rules/firewall.md
  shaper: ./settings/access-rules/shaper.md