structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  ad: ./settings/users/active-directory/README.md
  ad_authorization: ./settings/users/active-directory/README.md
  additionally: ./settings/services/additionally.md
  admins: ./settings/access-rules/admins.md
  antivirus: ./settings/access-rules/antivirus.md
  application_control: ./settings/access-rules/application-control.md
  backup: ./service/backup.md
  balancing_and_reserving: ./settings/services/multiple-simultaneous-connections.md
  certificate: ./settings/services/certificates/README.md
  custom_ssl: ./settings/services/certificates/upload-ssl-certificate-to-server.md
  cluster: ./settings/cluster.md
  content_filter: ./settings/access-rules/content-filter/README.md
  device_detection: ./settings/users/device-discovery.md
  dhcp: ./settings/services/dhcp.md
  firewall: ./settings/access-rules/firewall.md
  https_filtration: ./settings/access-rules/content-filter/filtering-https-traffic.md
  ids_ips: ./settings/access-rules/ips.md
  install: ./installation/installation-process.md
  ipsec: ./settings/services/ipsec/README.md
  license: ./service/server-registration.md
  reg: ./service/server-registration.md
  network_interface: ./settings/services/connection-to-provider/README.md
  dns: ./settings/services/dns.md
  nextdns: ./settings/services/nextdns.md
  dns_external: ./settings/services/dns.md
  object: ./settings/access-rules/aliases.md
  portmapping: ./settings/publishing-resources/portmapping.md
  post: ./settings/mail/README.md
  mail: ./settings/mail/README.md
  antispam: ./settings/mail/mail-server-settings.md
  powershell: ./settings/users/authorization/vpn-connection/running-powershell-scripts.md
  proxy: ./settings/services/proxy/README.md
  report: ./settings/reports/README.md
  reverse_proxy: ./settings/services/reverse-proxy.md
  routing: ./settings/services/routing.md
  server_registration: ./service/server-registration.md
  server_update: ./service/server-update.md
  snmp: ./settings/monitor/snmp.md
  speed_limit: ./settings/access-rules/shaper.md
  shaper: ./settings/access-rules/shaper.md
  support: ./service/remote-assistant.md
  syslog: ./settings/monitor/syslog.md
  telegram-bot: ./settings/monitor/telegram-bot.md
  telegram_bot: ./settings/monitor/telegram-bot.md
  terminal: ./settings/terminal.md
  usb: ./installation/usb.md
  user_authorization: ./settings/users/authorization/README.md
  user_management: ./settings/users/README.md
  user_quota: ./settings/access-rules/quotas.md
  vpn_authorization: ./settings/users/authorization/vpn-connection/README.md
  ideco_vpn_agent: ./settings/services/vpn-tunnel-protocols/client-to-site/ideco-vpn-client.md
  zabbix: ./settings/monitor/zabbix.md
  utm2cisco: ./settings/services/ipsec/site-to-site/connect-utm-to-cisco-via-ipsec.md
  auto-auth-script: ./settings/users/active-directory/auto-authorization-and-de-authorization-script.md
  auto-logout-script: ./settings/users/active-directory/auto-authorization-and-de-authorization-script.md
  dashboard: ./settings/monitor-panel.md
  traffmon: ./settings/monitor/traffic.md
  logs: ./settings/monitor/logs.md
  authorized: ./settings/monitor/authorized-users.md
  ospf: ./settings/services/ospf.md
  user_tree: ./settings/users/user-tree.md
  reports_sites: ./settings/reports/sites.md
  reports_user: ./settings/reports-user.md
  reports_categories: ./settings/category-reports.md
  reports_eventlog: ./settings/reports_eventlog.md
  reports_designer: ./settings/report-designer.md
  authorization_log: ./settings/reports/authorization-log.md
  license_management: ./service/license-management.md
  advanced_settings: ./settings/mail/advanced-settings.md
  antispam_chapter: ./settings/mail/antispam.md
  rules: ./settings/mail/regulations.md
  mail_queue: ./settings/mail/mail-queue.md