structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  ad: ./settings/users/active-directory/README.md
  additionally: ./settings/server-management/additionally.md
  admins: ./settings/server-management/admins.md
  antivirus: ./settings/access-rules/antivirus.md
  backup: ./settings/server-management/backup.md
  balancing_and_reserving: ./settings/services/multiple-simultaneous-connections.md
  certificate: ./settings/services/certificates/README.md
  custom_ssl: ./settings/services/certificates/upload-ssl-certificate-to-server.md
  cluster: ./settings/server-management/cluster/cluster.md
  content_filter: ./settings/access-rules/content-filter/README.md
  device_detection: ./settings/users/device-discovery.md
  dhcp: ./settings/services/dhcp.md
  firewall: ./settings/access-rules/firewall.md
  https_filtration: ./settings/access-rules/content-filter/filtering-https-traffic.md
  ids_ips: ./settings/access-rules/ips/README.md
  install: ./installation/installation-process.md
  ipsec: ./settings/services/ipsec/README.md
  network_interface: ./settings/services/connection-to-provider/README.md
  dns: ./settings/services/dns/README.md
  nextdns: ./settings/services/dns/nextdns.md
  object: ./settings/access-rules/aliases.md
  basic_settings: ./settings/mail/mail-server-settings/README.md
  powershell: ./settings/users/authorization/vpn-connection/running-powershell-scripts.md
  proxy: ./settings/services/proxy/README.md
  report: ./settings/reports/README.md
  reverse_proxy: ./settings/services/reverse-proxy.md
  routing: ./settings/services/routing.md
  server_registration: ./installation/server-registration.md
  reg: ./installation/server-registration.md
  server_update: ./settings/server-management/server-update.md
  snmp: ./settings/monitor/snmp.md
  shaper: ./settings/access-rules/shaper.md
  support: ./general/remote-assistant.md
  syslog: ./settings/reports/syslog.md
  telegram_bot: ./settings/monitor/telegram-bot.md 
  terminal: ./settings/server-management/terminal/README.md
  user_authorization: ./settings/users/authorization/README.md
  user_management: ./settings/users/README.md
  vpn_authorization: ./settings/users/authorization/vpn-connection/README.md
  zabbix: ./settings/monitor/zabbix.md
  dashboard: ./settings/monitor-panel.md
  traffmon: ./settings/monitor/traffic.md
  logs: ./settings/reports/logs.md
  authorized: ./settings/monitor/authorized-users.md
  ospf: ./settings/services/ospf.md
  user_tree: ./settings/users/user-tree/README.md
  reports_designer: ./settings/reports/report-designer.md
  authorization_log: ./settings/reports/authorization-log.md
  terminal_server_auth: ./settings/users/authorization/terminal-server.md
  license_management: ./general/license.md
  advanced_settings: ./settings/mail/advanced-settings/README.md
  antispam_chapter: ./settings/mail/antispam.md
  rules: ./settings/mail/regulations/README.md
  mail_queue: ./settings/mail/mail-queue.md
  bgp: ./settings/services/bgp.md
  traffic: ./settings/reports/traffic.md
  ideco_client: ./settings/users/ideco-client/README.md
  two_factor_authentication: ./settings/users/two-factor-authentication.md
  web_authorization: ./settings/users/authorization/web-authorization.md
  web_traffic_log: ./settings/reports/web-traffic-log.md
  ddns: ./settings/services/dns/ddns.md 
  ald_pro: ./settings/users/ald-pro.md 
  igmp_proxy: ./settings/services/igmp.md
  admin_logs: ./settings/reports/administrator-actions.md
  vpn_connection: ./settings/users/authorization/vpn-connection/README.md
  security_events: ./settings/reports/security-events.md
  exceptions: ./settings/access-rules/ips/user-ip-exceptions.md
  ntp: ./settings/services/ntp.md
  dhcp_option: ./settings/services/dhcp.md
  radius: ./settings/users/radius.md
  vce: ./settings/server-management/vce.md
  antivirus_log: ./settings/reports/antivirus-logs.md
  auto_logout_script: ./settings/users/active-directory/auto-de-authorization-script.md
  session_sync: ./settings/server-management/cluster/cluster.md
  cc: ./settings/server-management/central-console
  cc_firewall: ./settings-cc/policies-and-objects.md
  cc_content_filter: ./settings-cc/policies-and-objects.md
  cc_aliases: ./settings-cc/policies-and-objects.md
  cc_shaper: ./settings-cc/policies-and-objects.md
  cc_interfaces: ./settings-cc/services.md
  cc_routing: ./settings-cc/services.md
  cc_certs: ./settings-cc/services.md
  cc_dns: ./settings-cc/services.md
  cc_admins: ./settings-cc/server-management.md
  cc_selfupdate: ./settings-cc/server-management.md
  cc_backup: ./settings-cc/server-management.md
  cc_web_terminal: ./settings-cc/server-management.md
  cc_characteristics: ./settings-cc/server-management.md
  cc_additionally: ./settings-cc/server-management.md
  cc_zabbix: ./settings-cc/monitor.md
  cc_snmp: ./settings-cc/monitor.md
  cc_dpi: ./settings-cc/security-profiles.md
  cc_ids_ips: ./settings-cc/security-profiles.md
  cc_waf_security_profiles: ./settings/security-profiles/waf-profiles.md
  cc_logs: ./settings-cc/reports.md
  cc_admin_logs: ./settings-cc/reports.md
  device-profiles: ./settings/users/hip-profiles.md
  dhcp_wpad: ./settings/services/dhcp.md
  user_personal_account: ./settings/services/user-personal-account.md
  waf_security_profiles: ./settings/security-profiles/waf-profiles.md
  source_port: ./settings/access-rules/firewall-tables.md
  administrator_sessions: ./settings/monitor/administrator-sessions.md
  dpi: ./settings/security-profiles/application-control/README.md
  version_support: ./general/support-period.md
  ips_profiles: ./settings/security-profiles/ips-profiles/README.md
  two_factor: ./settings/users/two-factor-authentication.md
  netflow: ./settings/monitor/netflow.md
  traffic_log: ./settings/reports/traffic-log.md
  usb_token: ./settings/services/usb_tokens.md
  tokens: ./settings/services/usb_tokens.md
  gost-vpn: ./settings/services/gost-vpn.md
  hardware_filtering: ./settings/access-rules/hardware-filtering.md
  personal_account_auth_log: ./settings/reports/personal-account-auth-log.md
  personal_account_sessions: ./settings/monitor/personal-account-sessions.md
